#! /bin/sh


sudo apt-get install -y     \
          texlive-latex-recommended \
          texlive-latex-extra       \
          texlive-fonts-recommended \
          texlive-fonts-extra       \
          texlive-xetex             \
          latexmk                   \
          xindy                     \
          dvipng                    \
          cm-super
sudo apt install texlive-latex-extra --fix-missing
sudo apt update && sudo apt install g++ libboost-all-dev libgsl-dev libhdf5-serial-dev
sudo apt-get install gcc libpq-dev -y
sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y