default_language_version:
    python: python3
repos:
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell # Spellchecker
        args: [-L, 'parms,hist,tHeI,Hist', --skip, '*.eps,*.svg']