import os
import time
from contextlib import redirect_stdout
from io import StringIO
from typing import Any

DETAILED_EVOLUTION_PATH = os.path.join(
        os.path.dirname(__file__),
        "../misc/examples/methods_paper_plots/detailed_evolution"
        )

def get_compas_output_path(clean=False):
    """Get the path to the COMPAS output file generated by the test suite."""
    compas_data_path = os.path.join(DETAILED_EVOLUTION_PATH, "COMPAS_Output/COMPAS_Output.h5")

    if not os.path.exists(compas_data_path) or clean:  # Check if path exists
        curr_dir = os.getcwd()
        os.chdir(DETAILED_EVOLUTION_PATH)
        os.system('python runSubmitDemo.py')
        os.chdir(curr_dir)
        print("Generated COMPAS test data")

    return compas_data_path


def time_func_and_capture_sout(func, *args, **kwargs)->(Any, float, str):
    """Time a function and capture stdout.

    :return: (func_out, dur, stdout)
    """
    func_out=None
    start = time.time()
    with redirect_stdout(StringIO()) as sout:
        func_out = func(*args, **kwargs)
    sout = sout.getvalue()
    end = time.time()
    dur = end - start
    return func_out, dur, sout