from enum import Enum, auto


class STELLAR_TYPE(Enum):
    MS_LTE_07 = 0
    MS_GT_07 = auto()
    HERTZSPRUNG_GAP = auto()
    FIRST_GIANT_BRANCH = auto()
    CORE_HELIUM_BURNING = auto()
    EARLY_ASYMPTOTIC_GIANT_BRANCH = auto()
    THERMALLY_PULSING_ASYMPTOTIC_GIANT_BRANCH = auto()
    NAKED_HELIUM_STAR_MS = auto()
    NAKED_HELIUM_STAR_HERTZSPRUNG_GAP = auto()
    NAKED_HELIUM_STAR_GIANT_BRANCH = auto()
    HELIUM_WHITE_DWARF = auto()
    CARBON_OXYGEN_WHITE_DWARF = auto()
    OXYGEN_NEON_WHITE_DWARF = auto()
    NEUTRON_STAR = auto()
    BLACK_HOLE = auto()
    MASSLESS_REMNANT = auto()
    CHEMICALLY_HOMOGENEOUS = auto()
    STAR = auto()
    BINARY_STAR = auto()
    NONE = auto()

BH = [STELLAR_TYPE.BLACK_HOLE]
NS = [STELLAR_TYPE.NEUTRON_STAR]
WD = [STELLAR_TYPE.HELIUM_WHITE_DWARF,
      STELLAR_TYPE.CARBON_OXYGEN_WHITE_DWARF,
      STELLAR_TYPE.HELIUM_WHITE_DWARF,
      STELLAR_TYPE.OXYGEN_NEON_WHITE_DWARF]

