name: Compile LaTeX
on: 
  pull_request: 
    branches: [dev]

jobs:
  compile_latex:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up git repo
        uses: actions/checkout@v2

      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          working_directory: docs/COMPAS_LaTeX
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape

      - name: bibtex main
        uses: dante-ev/latex-action@latest
        with:
          working_directory: docs/COMPAS_LaTeX
          root_file: main.aux
          compiler: bibtex 
          args: 

      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          working_directory: docs/COMPAS_LaTeX
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape
