name: Comment on Pull request

on:
  workflow_run:
    workflows: ['COMPAS compile test']
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set up GitHub CLI
        uses: actions/setup-gh@v2
        with:
          version: latest

      - name: Auth GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Get Artifact and Pull request info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_RUN_EVENT_OBJ: ${{ toJSON(github.event.workflow_run) }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          PREVIOUS_JOB_ID=$(jq -r '.id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
          echo "PREVIOUS_JOB_ID=$PREVIOUS_JOB_ID" >> "$GITHUB_ENV"
          
          SUITE_ID=$(jq -r '.check_suite_id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
          echo "SUITE_ID=$SUITE_ID" >> "$GITHUB_ENV"
          
          # Retry loop to wait for artifact availability
          for i in {1..5}; do
            ARTIFACT_ID=$(gh api "/repos/$OWNER/$REPO/actions/artifacts" \
              --jq ".artifacts[] | select(.workflow_run.id==$PREVIOUS_JOB_ID and .expired==false and .name==\"detailedEvolutionPlot.png\") | .id" | head -n1)
            if [[ -n "$ARTIFACT_ID" ]]; then break; fi
            echo "Artifact not found yet. Retrying in 10s..."
            sleep 10
          done
          echo "ARTIFACT_ID=$ARTIFACT_ID" >> "$GITHUB_ENV"
          
          PR_NUMBER=$(gh api "/repos/$OWNER/$REPO/commits/${{ github.event.workflow_run.head_sha }}/pulls" --jq '.[0].number')
          echo "PR_NUMBER=${PR_NUMBER:-null}" >> "$GITHUB_ENV"
          
          HEAD_SHA=${{ github.event.workflow_run.head_sha }}
          echo "HEAD_SHA=$HEAD_SHA" >> "$GITHUB_ENV"

      - name: Download artifact
        if: env.PR_NUMBER != 'null' && env.ARTIFACT_ID != ''
        run: |
          gh api /repos/${{ github.repository }}/actions/artifacts/${{ env.ARTIFACT_ID }}/zip --output artifact.zip
          unzip artifact.zip
          rm artifact.zip

      - name: Update Comment
        if: env.PR_NUMBER != 'null' && env.ARTIFACT_ID != ''
        env:
          JOB_PATH: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ env.PREVIOUS_JOB_ID }}"
          ARTIFACT_DL: "${{ github.server_url }}/${{ github.repository }}/actions/artifacts/${{ env.ARTIFACT_ID }}"
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const imageData = fs.readFileSync('detailedEvolutionPlot.png', {encoding: 'base64'});
            github.rest.issues.createComment({
              issue_number: process.env.PR_NUMBER,
              owner: context.repo.owner,
              repo: context.repo.name,
              body: `
                ![badge]
                
                Build Successful! You can find a link to the downloadable artifact below.
                
                | Name     | Link                    |
                | -------- | ----------------------- |
                | Commit   | ${process.env.HEAD_SHA} |
                | Logs     | ${process.env.JOB_PATH} |
                | Download | ${process.env.ARTIFACT_DL} |
                
                ### Detailed Evolution Plot
                ![Detailed Evolution Plot](data:image/png;base64,${imageData})
                
                [badge]: https://img.shields.io/badge/Build_Success!-0d1117?style=for-the-badge&labelColor=3fb950
              `
            })