name: Compile and upload LaTeX
on: 
  push:
    branches: [dev]
  pull_request: 
    branches: [dev]
    types: [submitted]

jobs:
  test: 
    runs-on: ubuntu-18.04
    steps:
      - run: |
          echo "${{github.event}}"
      - run: |
          echo "${{github.event_name}}"
      - run: |
          echo "${{github.event.action}}"
      - run: |
          echo "${{github.event.type}}"
      - run: |
          echo "${{github.event.review.state}}"
      - run: |
          echo 'test 1'

        #echo github.event.review.state
        #if: github.event.review.state == 'approved'
      
  compile:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up git repo
        uses: actions/checkout@v2

      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          working_directory: docs/COMPAS_LaTeX
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape

      - name: bibtex main
        uses: dante-ev/latex-action@latest
        with:
          working_directory: docs/COMPAS_LaTeX
          root_file: main.aux
          compiler: bibtex 
          args: 

      - name: pdflatex main
        uses: dante-ev/latex-action@latest
        with:
          working_directory: docs/COMPAS_LaTeX
          root_file: main.tex
          compiler: pdflatex
          args: -interaction=nonstopmode -shell-escape

      # If the PR is approved, a push is sent to dev
      - name: upload pdf
        #if: ${{github.event_name}} == push
        run: |
          git checkout --orphan Documentation
          PDF_FILE=COMPAS_Documentation.pdf
          mv docs/COMPAS_LaTeX/main.pdf $PDF_FILE
          git rm -rf .
          git add -f $PDF_FILE
          git -c user.name='reinhold-willcox' -c user.email='reinhold.willcox@mail.mcgill.ca' commit -m "documentation update"
          git push -f --set-upstream origin Documentation


